Pos/Controllers/ArticuloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using Pos.Models;

namespace FacturaWebLG.Controllers
{
    public class ArticuloController : Controller
    {
        //PosEntities es mi Contexto

        public ActionResult Index()
        {
            try
            {
                using (var db = new VentasEntities())
                {
                    List<Articulo> lista = db.Articulo.Where(a => a.Activo == true).ToList();
                    return View(lista);
                }

            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Articulo item)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new VentasEntities())
                {
                    if (IsDuplicate(item.Codigo, item.id))
                    {
                        ModelState.AddModelError("", "Verifique, ya existe otro artículo con código: " + item.Codigo);
                        return View();
                    }
                    else
                    {
                        db.Articulo.Add(item);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Error al crear nuevo artículo: " + ex.Message);
                return View();
            }

        }

        public ActionResult Details(int id)
        {
            try
            {
                using (var db = new VentasEntities())
                {
                    Articulo item = db.Articulo.Find(id);
                    return View(item);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new VentasEntities())
                {
                    Articulo item = db.Articulo.Find(id);
                    return View(item);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Articulo item)
        {
            try
            {
                using (var db = new VentasEntities())
                {
                    if (IsDuplicate(item.Codigo, item.id))
                    {
                        ModelState.AddModelError("", "Verifique, ya existe otro artículo con código: " + item.Codigo);
                        return View();
                    }
                    else
                    {
                        Articulo art = db.Articulo.Find(item.id);
                        art.Codigo = item.Codigo;
                        art.Descripcion = item.Descripcion;
                        art.Precio = item.Precio;
                        art.Costo = item.Costo;
                        art.Existencia = item.Existencia;

                        db.Entry(art).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");

                    }
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "Error al actualizar artículo: " + ex.Message);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new VentasEntities())
                {
                    Articulo item = db.Articulo.Find(id);
                    db.Articulo.Remove(item);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public bool IsDuplicate(string codigo, int id)
        {
            using (var db = new VentasEntities())
            {
                if (db.Articulo.Any(x => x.Codigo == codigo && x.id != id))
                {
                    return true;
                }
                else
                {
                    return false;
                }

            }

        }
    }
}

Pos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="padding-top:0px">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
            @Html.ActionLink("Pos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav justify-content-end">
                    <li class="nav-item">@Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contacto", "Contact", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Artículo", "Index", "Articulo", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Factura", "Index", "Factura", null, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>

    <header class="jumbotron" style="padding: 32px 32px 0px 32px">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-sm-8">
                    <h1>Facturación</h1>
                    <p>Aplicación desarrollada usando ASP.NET MVC 5.2, Entity Framework 6.0.0 and Linq.  Font Awesome, Bootstrap 4</p>
                </div>
                <div class="col-12 col-sm-4" style="margin-bottom: 20px;">
                    <img src="~/img/invoice.png" class="img-fluid" height="240" width="320">
                </div>
            </div>
        </div>
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr class="mt-5" />
        <footer>
            <p>&copy; @DateTime.Now.Year - WPereira </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>